
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://ksp2mars.org"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "KSP2Mars"
title: "KSP2Mars"
description: "Kerbal Space Program Community Mars Mission"
keywords: "mars, space, ksp, kerbal space program"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/favicon.ico"

background-img: "https://blog.ksp2mars.org/assets/images/mars-surface1-min.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Astronomy compels the soul to look upward, and leads us from this world to another. — Plato"
  - text: "The wonder is, not that the field of stars of so vast, but that man has measured it. — Anatole France"
  - text: "Equipped with his five senses, man explores the universe around him and calls the adventure Science. — Edwin Hubble"
  - text: "What are we doing here? We're reaching for the stars. — Christa McAuliffe"
  - text: "I'd like to die on Mars. Just not on impact. — Elon Musk"

me-img: "https://blog.ksp2mars.org/assets/images/ksp2marsv1.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

# disqus-shortname: ""

syntax-highlight: False

############
# Timeline #
############

events:
  - image: "/img/timeline/design1.png"
#    date: "September 2013 - Today"
    description: "Design"
  - image: "/img/timeline/test1.png"
#    date: "September 2007 - August 2013"
    description: "Test"
  - image: "/img/timeline/launch1.png"
#    date: "September 2007 - August 2013"
    description: "Launch!"

# First image of the Timeline

timeline-img: "https://blog.ksp2mars.org/assets/images/ksp2marsv1.png"

###########
# Contact #
###########

email: "hello@ksp2mars.org"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/ksp2mars"
#  - title: "github"
#    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "https://blog.ksp2mars.org/feed.xml"

############
# 404 page #
############

err-404-img: "https://blog.ksp2mars.org/assets/images/ksp2marsv1.png"

##################
# GPG on Keybase #
##################

keybase-username: ksp2mars
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "p/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
